import type { Metadata } from "next";
import { fonts } from "@/constants";
import "../public/styles/css/globals.css";

export const metadata: Metadata = {
  title: "Testing Prisma with Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode;}>) {
  const { geistMono, geistSans } = fonts;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
